---
- name: create users
  hosts: "{{ host }}"
  become: true
  vars:
    debug_enabled_default: false
    users:
    - username: '{{ username }}'
      comment: '{{ comment }}'
      password: '{{ password_username }}'
      update_password: always
      groups: netdev
      shell: /bin/bash
      use_sudo: no
      use_sudo_nopass: no
      user_state: present
      servers:
      - dev

    - username: tmpadmin
      comment: Tmp Admin
      update_password: always
      password: "{{ password_tmpadmin }}"
      groups: sudo
      use_sudo: yes
      shell: /bin/bash
      user_state: present
      servers: 
      - dev

  roles:
  - create-users